# Generated by Django 5.0.6 on 2026-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_address_order_address_1_order_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
