# Generated by Django 5.0.6 on 2026-01-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('N/A', 'No Aplica'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='N/A', max_length=5),
        ),
    ]
