# Generated by Django 5.0.6 on 2026-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_size_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category']},
        ),
        migrations.AddField(
            model_name='product',
            name='requires_size',
            field=models.BooleanField(default=False),
        ),
    ]
